# Generated by Django 3.0.2 on 2020-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
    ]
