# Generated by Django 3.0.2 on 2020-01-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200128_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Section'),
        ),
    ]
