# Generated by Django 3.0.2 on 2020-01-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='who',
            new_name='who_id',
        ),
    ]
