# Generated by Django 3.0.2 on 2020-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200128_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='when',
            field=models.DateField(),
        ),
    ]
